### PR TITLE
WIP Port to MC2

### PR DESCRIPTION
**Pull request by proux01**
Mathcomp 2 has been released more than a year ago and this is the last thing not yet proted in Coq's CI.
Here is a large part of the port but I don't have time to complete it myself. Could you please have a look (I can help with the Hierarchy-Builder details).

### CODE REVIEW

**Comment by aleksnanevski** [comment]
I have been working on a port myself (of this, and other stuff of mine). Should all be done by the end of the summer. Not sure if it makes sense to merge this now.

**Comment by proux01** [comment]
No, this doesn't entirely compile so definitely not mergeable.

**Comment by aleksnanevski** [comment]
Is it then OK for you guys to wait on me a bit longer?

**Comment by proux01** [comment]
Sure, end of summer is definitely fine, and feel free to ask if you encounter any difficulty.

**Comment by aleksnanevski** [comment]
Great, thanks! No real difficulties really. It has taken long time because I decided to completely change all the code (not just to get a port to mathcomp2, but also to change the organization of the math underneath). In the meantime, I should say, I have grown to quite like HB.

**Pull request closed without merging**
